# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /shared/earth/software/CMake/3.2.2-foss-2015a/bin/cmake

# The command to remove a file.
RM = /shared/earth/software/CMake/3.2.2-foss-2015a/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Earth/jvegas/CDFTOOLS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Earth/jvegas/CDFTOOLS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/shared/earth/software/CMake/3.2.2-foss-2015a/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/shared/earth/software/CMake/3.2.2-foss-2015a/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Earth/jvegas/CDFTOOLS/CMakeFiles /home/Earth/jvegas/CDFTOOLS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Earth/jvegas/CDFTOOLS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cdfio

# Build rule for target.
cdfio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cdfio
.PHONY : cdfio

# fast build rule for target.
cdfio/fast:
	$(MAKE) -f CMakeFiles/cdfio.dir/build.make CMakeFiles/cdfio.dir/build
.PHONY : cdfio/fast

#=============================================================================
# Target rules for targets named cdfmoy

# Build rule for target.
cdfmoy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cdfmoy
.PHONY : cdfmoy

# fast build rule for target.
cdfmoy/fast:
	$(MAKE) -f CMakeFiles/cdfmoy.dir/build.make CMakeFiles/cdfmoy.dir/build
.PHONY : cdfmoy/fast

#=============================================================================
# Target rules for targets named cdfmoyt

# Build rule for target.
cdfmoyt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cdfmoyt
.PHONY : cdfmoyt

# fast build rule for target.
cdfmoyt/fast:
	$(MAKE) -f CMakeFiles/cdfmoyt.dir/build.make CMakeFiles/cdfmoyt.dir/build
.PHONY : cdfmoyt/fast

#=============================================================================
# Target rules for targets named cdftools

# Build rule for target.
cdftools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cdftools
.PHONY : cdftools

# fast build rule for target.
cdftools/fast:
	$(MAKE) -f CMakeFiles/cdftools.dir/build.make CMakeFiles/cdftools.dir/build
.PHONY : cdftools/fast

#=============================================================================
# Target rules for targets named eos

# Build rule for target.
eos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eos
.PHONY : eos

# fast build rule for target.
eos/fast:
	$(MAKE) -f CMakeFiles/eos.dir/build.make CMakeFiles/eos.dir/build
.PHONY : eos/fast

#=============================================================================
# Target rules for targets named modcdfnames

# Build rule for target.
modcdfnames: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modcdfnames
.PHONY : modcdfnames

# fast build rule for target.
modcdfnames/fast:
	$(MAKE) -f CMakeFiles/modcdfnames.dir/build.make CMakeFiles/modcdfnames.dir/build
.PHONY : modcdfnames/fast

#=============================================================================
# Target rules for targets named modpoly

# Build rule for target.
modpoly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modpoly
.PHONY : modpoly

# fast build rule for target.
modpoly/fast:
	$(MAKE) -f CMakeFiles/modpoly.dir/build.make CMakeFiles/modpoly.dir/build
.PHONY : modpoly/fast

#=============================================================================
# Target rules for targets named modutils

# Build rule for target.
modutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modutils
.PHONY : modutils

# fast build rule for target.
modutils/fast:
	$(MAKE) -f CMakeFiles/modutils.dir/build.make CMakeFiles/modutils.dir/build
.PHONY : modutils/fast

cdfio.o: cdfio.F90.o
.PHONY : cdfio.o

# target to build an object file
cdfio.F90.o:
	$(MAKE) -f CMakeFiles/cdfio.dir/build.make CMakeFiles/cdfio.dir/cdfio.F90.o
.PHONY : cdfio.F90.o

cdfio.i: cdfio.F90.i
.PHONY : cdfio.i

# target to preprocess a source file
cdfio.F90.i:
	$(MAKE) -f CMakeFiles/cdfio.dir/build.make CMakeFiles/cdfio.dir/cdfio.F90.i
.PHONY : cdfio.F90.i

cdfio.s: cdfio.F90.s
.PHONY : cdfio.s

# target to generate assembly for a file
cdfio.F90.s:
	$(MAKE) -f CMakeFiles/cdfio.dir/build.make CMakeFiles/cdfio.dir/cdfio.F90.s
.PHONY : cdfio.F90.s

cdfmoy.o: cdfmoy.f90.o
.PHONY : cdfmoy.o

# target to build an object file
cdfmoy.f90.o:
	$(MAKE) -f CMakeFiles/cdfmoy.dir/build.make CMakeFiles/cdfmoy.dir/cdfmoy.f90.o
.PHONY : cdfmoy.f90.o

cdfmoy.i: cdfmoy.f90.i
.PHONY : cdfmoy.i

# target to preprocess a source file
cdfmoy.f90.i:
	$(MAKE) -f CMakeFiles/cdfmoy.dir/build.make CMakeFiles/cdfmoy.dir/cdfmoy.f90.i
.PHONY : cdfmoy.f90.i

cdfmoy.s: cdfmoy.f90.s
.PHONY : cdfmoy.s

# target to generate assembly for a file
cdfmoy.f90.s:
	$(MAKE) -f CMakeFiles/cdfmoy.dir/build.make CMakeFiles/cdfmoy.dir/cdfmoy.f90.s
.PHONY : cdfmoy.f90.s

cdfmoyt.o: cdfmoyt.f90.o
.PHONY : cdfmoyt.o

# target to build an object file
cdfmoyt.f90.o:
	$(MAKE) -f CMakeFiles/cdfmoyt.dir/build.make CMakeFiles/cdfmoyt.dir/cdfmoyt.f90.o
.PHONY : cdfmoyt.f90.o

cdfmoyt.i: cdfmoyt.f90.i
.PHONY : cdfmoyt.i

# target to preprocess a source file
cdfmoyt.f90.i:
	$(MAKE) -f CMakeFiles/cdfmoyt.dir/build.make CMakeFiles/cdfmoyt.dir/cdfmoyt.f90.i
.PHONY : cdfmoyt.f90.i

cdfmoyt.s: cdfmoyt.f90.s
.PHONY : cdfmoyt.s

# target to generate assembly for a file
cdfmoyt.f90.s:
	$(MAKE) -f CMakeFiles/cdfmoyt.dir/build.make CMakeFiles/cdfmoyt.dir/cdfmoyt.f90.s
.PHONY : cdfmoyt.f90.s

cdftools.o: cdftools.f90.o
.PHONY : cdftools.o

# target to build an object file
cdftools.f90.o:
	$(MAKE) -f CMakeFiles/cdftools.dir/build.make CMakeFiles/cdftools.dir/cdftools.f90.o
.PHONY : cdftools.f90.o

cdftools.i: cdftools.f90.i
.PHONY : cdftools.i

# target to preprocess a source file
cdftools.f90.i:
	$(MAKE) -f CMakeFiles/cdftools.dir/build.make CMakeFiles/cdftools.dir/cdftools.f90.i
.PHONY : cdftools.f90.i

cdftools.s: cdftools.f90.s
.PHONY : cdftools.s

# target to generate assembly for a file
cdftools.f90.s:
	$(MAKE) -f CMakeFiles/cdftools.dir/build.make CMakeFiles/cdftools.dir/cdftools.f90.s
.PHONY : cdftools.f90.s

eos.o: eos.f90.o
.PHONY : eos.o

# target to build an object file
eos.f90.o:
	$(MAKE) -f CMakeFiles/eos.dir/build.make CMakeFiles/eos.dir/eos.f90.o
.PHONY : eos.f90.o

eos.i: eos.f90.i
.PHONY : eos.i

# target to preprocess a source file
eos.f90.i:
	$(MAKE) -f CMakeFiles/eos.dir/build.make CMakeFiles/eos.dir/eos.f90.i
.PHONY : eos.f90.i

eos.s: eos.f90.s
.PHONY : eos.s

# target to generate assembly for a file
eos.f90.s:
	$(MAKE) -f CMakeFiles/eos.dir/build.make CMakeFiles/eos.dir/eos.f90.s
.PHONY : eos.f90.s

modcdfnames.o: modcdfnames.f90.o
.PHONY : modcdfnames.o

# target to build an object file
modcdfnames.f90.o:
	$(MAKE) -f CMakeFiles/modcdfnames.dir/build.make CMakeFiles/modcdfnames.dir/modcdfnames.f90.o
.PHONY : modcdfnames.f90.o

modcdfnames.i: modcdfnames.f90.i
.PHONY : modcdfnames.i

# target to preprocess a source file
modcdfnames.f90.i:
	$(MAKE) -f CMakeFiles/modcdfnames.dir/build.make CMakeFiles/modcdfnames.dir/modcdfnames.f90.i
.PHONY : modcdfnames.f90.i

modcdfnames.s: modcdfnames.f90.s
.PHONY : modcdfnames.s

# target to generate assembly for a file
modcdfnames.f90.s:
	$(MAKE) -f CMakeFiles/modcdfnames.dir/build.make CMakeFiles/modcdfnames.dir/modcdfnames.f90.s
.PHONY : modcdfnames.f90.s

modpoly.o: modpoly.f90.o
.PHONY : modpoly.o

# target to build an object file
modpoly.f90.o:
	$(MAKE) -f CMakeFiles/modpoly.dir/build.make CMakeFiles/modpoly.dir/modpoly.f90.o
.PHONY : modpoly.f90.o

modpoly.i: modpoly.f90.i
.PHONY : modpoly.i

# target to preprocess a source file
modpoly.f90.i:
	$(MAKE) -f CMakeFiles/modpoly.dir/build.make CMakeFiles/modpoly.dir/modpoly.f90.i
.PHONY : modpoly.f90.i

modpoly.s: modpoly.f90.s
.PHONY : modpoly.s

# target to generate assembly for a file
modpoly.f90.s:
	$(MAKE) -f CMakeFiles/modpoly.dir/build.make CMakeFiles/modpoly.dir/modpoly.f90.s
.PHONY : modpoly.f90.s

modutils.o: modutils.f90.o
.PHONY : modutils.o

# target to build an object file
modutils.f90.o:
	$(MAKE) -f CMakeFiles/modutils.dir/build.make CMakeFiles/modutils.dir/modutils.f90.o
.PHONY : modutils.f90.o

modutils.i: modutils.f90.i
.PHONY : modutils.i

# target to preprocess a source file
modutils.f90.i:
	$(MAKE) -f CMakeFiles/modutils.dir/build.make CMakeFiles/modutils.dir/modutils.f90.i
.PHONY : modutils.f90.i

modutils.s: modutils.f90.s
.PHONY : modutils.s

# target to generate assembly for a file
modutils.f90.s:
	$(MAKE) -f CMakeFiles/modutils.dir/build.make CMakeFiles/modutils.dir/modutils.f90.s
.PHONY : modutils.f90.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cdfmoyt"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cdftools"
	@echo "... cdfmoy"
	@echo "... eos"
	@echo "... modcdfnames"
	@echo "... cdfio"
	@echo "... modpoly"
	@echo "... modutils"
	@echo "... cdfio.o"
	@echo "... cdfio.i"
	@echo "... cdfio.s"
	@echo "... cdfmoy.o"
	@echo "... cdfmoy.i"
	@echo "... cdfmoy.s"
	@echo "... cdfmoyt.o"
	@echo "... cdfmoyt.i"
	@echo "... cdfmoyt.s"
	@echo "... cdftools.o"
	@echo "... cdftools.i"
	@echo "... cdftools.s"
	@echo "... eos.o"
	@echo "... eos.i"
	@echo "... eos.s"
	@echo "... modcdfnames.o"
	@echo "... modcdfnames.i"
	@echo "... modcdfnames.s"
	@echo "... modpoly.o"
	@echo "... modpoly.i"
	@echo "... modpoly.s"
	@echo "... modutils.o"
	@echo "... modutils.i"
	@echo "... modutils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

