#!/bin/ksh
#set -xv
# Shell functions
# check existence and eventually create directory
chkdir() { if [ ! -d $1 ] ; then mkdir $1 ; fi ; }

# Checck if the current dir is a xxx-xx-S directory
here=$(basename $( pwd ) )
ext=$( echo $here | sed -e 's/-/ /g' | awk '{print $3}' )

if [ ${ext:-none}  != 'S' ] ; then 
  echo 'you are not in an -S directory. You cannot mkordre :('
  exit 1
fi

# Move annex tarfiles to ANNEX
ls *anne*  2> /dev/null && { chkdir ANNEX ; mv *anne* ANNEX  ; }

# Scan the different types of files and send then to the YEAR directory
for type in gridT gridU gridV gridW icemod ptrcT trends dynT flxT; do
  ls *${type}.nc  2> /dev/null &&  { \
  for f in *_${type}.nc ; do 
    tag=$( echo $f | sed -e 's/_/ /g' | awk '{print $2}' )
    year=$( echo $tag | sed -e's/m/ /' | awk '{print $1}' | tr -d 'y' )

    chkdir $year
    mv $f $year
  done  ; }
done
  


