=head1  NAME

cdftools - diagnostics in Fortran 90 for NEMO model outputs

=head1 SYNOPSIS

 cdf* option...

=head1 DESCRIPTION

C<CDFTOOLS> is a diagnostic package written in fortran 90
for the analysis of NEMO model output in the frame of the DRAKKAR project.

This software is a computer program for analysis of NEMO model output 
produced in the frame of the DRAKKAR project. It is designed  for the
treatment of the NetCdf files produced by NEMO-DRAKKAR. 

C<NEMO> web site : http://www.nemo-ocean.eu/

=head1 COMMAND

